version: "3.8"
services:
  django:
#    image: ryechus/scavenger-wagtail:0e80cdc1f71433e9166fe9499daa0b5c811f6d09
    build:
      context: ./app/cms/scavenger
      dockerfile: Minimal.Dockerfile
      args:
        requirements: requirements.in requirements-dev.in requirements-prod.in
        docker_image_tag: base-bd1db91
    command:
      - ./manage.py
      - runserver
      - 0.0.0.0:8000
#    command:
#      - gunicorn
#      - -w
#      - "1"
#      - --bind=0.0.0.0:8000
#      - scavenger.wsgi
#      - --reload
    working_dir: /app/scavenger
    environment:
      - DJANGO_SETTINGS_MODULE=scavenger.settings.local
      - DJANGO_SECRET_KEY='test'
    volumes:
      - ./app/cms/scavenger:/app/scavenger
    ports:
      - 8000:8000
  fluentd:
    image: fluent/fluent-bit:1.9.1
#    depends_on:
#      - postgres
#  postgres:
#    image: postgres
#    env_file:
#      - .env.postgres
