apiVersion: batch/v1
kind: Job
metadata:
  name: cms-django-superuser
spec:
  template:
    spec:
      containers:
        - name: cms-django-superuser
          image: registry.scavenger.news/scavenger_blog:b28fa2d2a266dbeb9cccb73f731f365223105a16
          command:
            - ./manage.py
            - createsuperuser
            - --no-input
          env:
            - name: DJANGO_SUPERUSER_PASSWORD
              value: Xo6cnG93etSv
            - name: DJANGO_SUPERUSER_USERNAME
              value: mike
            - name: DJANGO_SUPERUSER_EMAIL
              value: admin@scavenger.news
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_PORT
      restartPolicy: Never
  backoffLimit: 4
