---
apiVersion: v1
kind: Service
metadata:
  name: cms
spec:
  selector:
    app: cms
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-deployment
  labels:
    app: cms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      imagePullSecrets:
        - name: docker.io.auth
      containers:
      - name: cms-django
        command:
          - gunicorn
          - -w
          - "3"
          - --bind=0.0.0.0:8000
          - --keep-alive
          - "10"
          - scavenger.wsgi
#          - scavenger.asgi
#          - -k
#          - uvicorn.workers.UvicornWorker
        image: ryechus/scavenger-wagtail:7c6c5931b66bf93e8d0614b6c6599acd6d20fddd
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cms-db-connection
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: cms-db-connection
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: cms-db-connection
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: cms-db-connection
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cms-db-connection
              key: DB_PORT
        - name: AWS_S3_ACCESS_KEY_ID
          value: AKIASX6I5DXVPH54ZCEN
        - name: AWS_S3_SECRET_ACCESS_KEY
          value: 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
        - name: env
          value: dev
