apiVersion: batch/v1
kind: Job
metadata:
  name: cms-django-migrate
spec:
  template:
    spec:
      containers:
        - name: cms-django-migrate
          image: registry.scavenger.news/scavenger_blog:b28fa2d2a266dbeb9cccb73f731f365223105a16
          command:
            - ./manage.py
            - migrate
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: cms-db-connection
                  key: DB_PORT
      restartPolicy: Never
  backoffLimit: 4
