version: "3.8"
services:
  django:
    build:
      context: .
      dockerfile: Minimal.Dockerfile
      args:
        requirements: requirements.in requirements-dev.in requirements-prod.in
    command:
      - gunicorn
      - -w
      - "1"
      - --bind=0.0.0.0:8000
      - scavenger.wsgi
      - --reload
    working_dir: /app/scavenger
#    env_file:
#      - .env.local
#      - .env.db-local
#      - local-dev.env
    environment:
      - DJANGO_SETTINGS_MODULE=scavenger.settings.local
      - DJANGO_SECRET_KEY='test'
    volumes:
      - ./:/app/scavenger
    ports:
      - 8000:8000
#    depends_on:
#      - postgres
#  postgres:
#    image: postgres
#    env_file:
#      - .env.postgres
