# Generated by Django 3.2.10 on 2022-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimages",
            name="base64_bin",
            field=models.BinaryField(null=True),
        ),
    ]
