# Generated by Django 4.0 on 2022-09-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailvideos", "0012_remove_unique_constraint"),
        ("posts", "0002_post_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimages",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="video_posts",
                to="wagtailvideos.video",
            ),
        ),
    ]
