# Generated by Django 3.2.12 on 2022-03-13 18:32

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('posts', '0002_postimages_base64_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artists',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='artists.Artist', to='artists.ArtistTag', verbose_name='Tags'),
        ),
    ]
