# Generated by Django 4.0 on 2022-09-11 07:33

import django.db.models.deletion
import scavenger.storage
import wagtail.images.models
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_uuid_alter_postimages_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageServiceImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("width", models.IntegerField(editable=False, verbose_name="width")),
                ("height", models.IntegerField(editable=False, verbose_name="height")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                ("focal_point_x", models.PositiveIntegerField(blank=True, null=True)),
                ("focal_point_y", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "focal_point_width",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "focal_point_height",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("file_size", models.PositiveIntegerField(editable=False, null=True)),
                (
                    "file_hash",
                    models.CharField(blank=True, editable=False, max_length=40),
                ),
                (
                    "file",
                    models.ImageField(
                        height_field="height",
                        storage=scavenger.storage.ImageServiceStorage,
                        upload_to=wagtail.images.models.get_upload_to,
                        width_field="width",
                    ),
                ),
            ],
            options={
                "db_table": "wagtailimages_image",
                "managed": False,
            },
            bases=(
                wagtail.images.models.ImageFileMixin,
                wagtail.search.index.Indexed,
                models.Model,
            ),
        ),
        migrations.AlterField(
            model_name="postimages",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_images",
                to="posts.imageserviceimagemodel",
            ),
        ),
    ]
