# Generated by Django 4.0 on 2022-09-27 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("wagtailvideos", "0012_remove_unique_constraint"),
        ("images", "0001_initial"),
        ("posts", "0005_imageserviceimagemodel_alter_postimages_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimages",
            name="image_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_images_new",
                to="images.imageserviceimagemodel",
            ),
        ),
        migrations.AlterField(
            model_name="postimages",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_images",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="postimages",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="video_posts",
                to="wagtailvideos.video",
            ),
        ),
        migrations.DeleteModel(
            name="ImageServiceImageModel",
        ),
    ]
