# Generated by Django 3.2.12 on 2022-03-13 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimages_base64_bin'),
        ('home', '0003_homepage_spotlight_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='spotlight_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spotlight_parent', to='posts.post'),
        ),
    ]
