# coding: utf-8

"""
    Auction API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from scavenger_auctions.apis.auctions_api import router as AuctionsApiRouter
from scavenger_auctions.apis.bids_api import router as BidsApiRouter
from scavenger_auctions.sql_models.core import create_db_and_tables

app = FastAPI(
    title="Auction API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)


@app.on_event("startup")
def on_startup():
    create_db_and_tables()


app.include_router(AuctionsApiRouter)
app.include_router(BidsApiRouter)
