---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scavenger-cms.fullname" . }}
  labels:
    {{- include "scavenger-cms.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "scavenger-cms.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scavenger-cms.fullname" . }}
  labels:
    {{- include "scavenger-cms.labels" . | nindent 4 }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scavenger-cms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scavenger-cms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Release.Name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - NEW_RELIC_CONFIG_FILE=/root/newrelic.ini
            - newrelic-admin
            - run-program
            - gunicorn
            - -w
            - "3"
            - "--bind=0.0.0.0:{{ .Values.service.port }}"
            - --keep-alive
            - "10"
            - scavenger.wsgi
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
          - name: newrelic-ini
            mountPath: /root/newrelic.ini
            subPath: newrelic.ini
          env:
            {{- toYaml .Values.cms.env_vars | nindent 12 }}
            - name: env
              value: {{ .Values.environment.name }}
            - name: SOURCE_CODE_VERSION
              value: {{ .Values.image.tag | default .Release.Name }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: newrelic-ini
          configMap:
            name: newrelic-ini
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
